### ISSUE TITLE
text search

### ISSUE THREAD

**Issue by stupax** [arve0/feathers-mongodb-fuzzy-search#15]
Hi, 
searchCall.find({ query: { $search: mySearchTerm } })
Is not bringing anything back?

Its working when i change $search to 
searchCall.find({ query: { $text: search.searchTerm } })
this works but is not filtering properly?

I am using mongoDB as well,

What am i doing wrong?

**Comment by arve0** [comment]
Hi! Please supply a working example that replicates the behaviour.

**Comment by stupax** [comment]
Thanks for the quick reply, got it working. Didn't index it properly.
