### ISSUE TITLE
Method: find: unknown top level operator: $regex

### ISSUE THREAD

**Issue by frostbytedata** [arve0/feathers-mongodb-fuzzy-search#5]
I believe I am doing something wrong here to see this message when my service method is called:
`Method: find: unknown top level operator: $regex`

Here are my service hooks:
```
const search = require('feathers-mongodb-fuzzy-search');
module.exports = {
  before: {
    all: [],
    find: [
      search({  // regex search on given fields
        fields: ['name']
      })
    ],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  },

  after: {
    all: [],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  },

  error: {
    all: [],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  }
};
```
And the GET request I am making as a URL: `GET /customers?$search=sharon`

I read through the README, but don't think I am missing anything. Of course I used `npm install` to add the plugin. Any ideas? Thanks!

**Comment by arve0** [comment]
Which version of MongoDB do you have?

**Comment by frostbytedata** [comment]
It appears I am using v3.4.10

**Comment by frostbytedata** [comment]
And the

**Comment by claustres** [comment]
I added an integration test for the REST API https://github.com/arve0/feathers-mongodb-fuzzy-search/pull/6, it seems to work fine. I also use Mongo 3.4.1.

**Comment by nathanstaines** [comment]
@claustres correct me if i'm wrong but it looks as if those tests are for the messages service which is only doing a full text search and therefore isn't actually using $regex?

**Comment by claustres** [comment]
Yes you are right but it is an integration test, it ensures the module still works when called from an external provider instead of internally.

Anyway I also added a test for the `users` service which uses `$regex`.

**Comment by nathanstaines** [comment]
@frostbytedata can you try `/customers?name[$search]=sharon` and see if that works for you?

**Comment by claustres** [comment]
I tested it locally since I prefer to use the request library to make sure the URL is correctly formatted in tests and it works as well. We might integrate the feathers client library to make integration test still one level up but not sure if it is required.

**Comment by frostbytedata** [comment]
I will test this as soon as I'm back at my desk. Thanks for the replies guys.

**Comment by frostbytedata** [comment]
@nathanstaines Nathan this syntax works!! Thanks a bunch!! So was this just me acting like a fool? or Is there a discrepancy in the README? Thanks again guys!!

**Comment by claustres** [comment]
Regex requires a field to search on in the query, cf. https://github.com/arve0/feathers-mongodb-fuzzy-search#usage.

**Comment by claustres** [comment]
Well not sure how we can unify since it seems to be a little bit different. In this module the field search allow you to search for different patterns on different fields *simultaneously* like `{ firstName: { $search: 'ay' }, lastName: { $search: 'b' } }`. If I understand it well the other module allows you to select which fields will be used for the full-text search but not to query fields individually.

If you want to use both with the same code you should only use the common feature of the full-text search and not the field matching feature, so use only `search()` without the fields option. With this module which fields are used to perform the full-text search is based on the MongoDB indexes.

**Comment by arve0** [comment]
Adding: Field search can be implemented in NeDB too, the code should be similar to this plugin. See https://github.com/louischatriot/nedb#operators-lt-lte-gt-gte-in-nin-ne-exists-regex

@rayfoss Please open an issue at feathers-nedb-fuzzy-search, so we can track it where it belongs.
