### ISSUE TITLE
error for full-text-search: createIndex of undefined

### ISSUE THREAD

**Issue by raphaklaus** [arve0/feathers-mongodb-fuzzy-search#7]
Hello,

I'm using mongoose to create the services, using feathers service generator for mongoose.
But when I try to create an index I get this error:

    Cannot read property 'createIndex' of undefined

doing like that:
    const service = app.service('products');
    service.Model.createIndex({title: 'text'});

I think this issue could be related to the fact I'm using mongoose instead of mongo pure driver.

**MongoDB version: 3.4.10**

**Comment by arve0** [comment]
http://mongoosejs.com/docs/api.html#schema_Schema-index

**Comment by raphaklaus** [comment]
Thank you for your reply.

Yes, you can use the mongoose `index` method to do that. But for new people (like me) getting started in Feathers can think that `createIndex` is a wrapper for indexing creation.

What do you think of putting something like that in the README.md? 

```
// create a text index on title property, for full-text search
// you may add multiple fields to the text index
// see the mongodb documentation for more on $text
const messages = app.service('messages')
// If you're using directly mongoDB:
messages.Model.createIndex({ title: 'text' })
// or if you're using mongoose.
// messages.Model.index({  title: 'text' })
```

**Comment by arve0** [comment]
Sure, that sounds like a good idea. Send me a PR :octocat:

**Comment by arve0** [comment]
Btw, why are you using mongoose? (Genuinely wondering)

**Comment by raphaklaus** [comment]
I'll do it!

Since Feathers deal with all the "raw" queries, it doesn't make difference but I'm used to its API so if I need to write something manually it's gonna be easier for me.
